/********************************************************************************
** Form generated from reading UI file 'hsm_full.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HSM_FULL_H
#define UI_HSM_FULL_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "qwt_plot.h"

QT_BEGIN_NAMESPACE

class Ui_hsm_full
{
public:
    QAction *actionCalibration;
    QAction *actionInterlocks;
    QAction *actionSet_Up_Model;
    QAction *actionPlot_Model;
    QWidget *centralWidget;
    QwtPlot *qwtPlot;
    QPushButton *SpanButton;
    QLCDNumber *CurPos;
    QLCDNumber *Offset;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLCDNumber *CurSpan;
    QLabel *label_4;
    QLabel *label_5;
    QLCDNumber *Force;
    QLabel *label_6;
    QPushButton *CommandButton;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QPushButton *ForcePID;
    QPushButton *DispPID;
    QDoubleSpinBox *CommandInput;
    QDoubleSpinBox *SpanInput;
    QDoubleSpinBox *PInputDisp;
    QDoubleSpinBox *IInputDisp;
    QDoubleSpinBox *DInputDisp;
    QPushButton *zeroButton;
    QPushButton *SinButton;
    QDoubleSpinBox *AmpInput;
    QDoubleSpinBox *FreqInput;
    QPushButton *FreqButton;
    QPushButton *AmpButton;
    QPushButton *SweepButton;
    QPushButton *fZeroButton;
    QLCDNumber *Stiffness;
    QLabel *label_10;
    QPushButton *AmpTestButton;
    QLabel *label_11;
    QDoubleSpinBox *CommandInput_2;
    QLabel *label_12;
    QPushButton *CommandButton_2;
    QLCDNumber *CurSpan_2;
    QLabel *label_13;
    QLCDNumber *CurPos_2;
    QDoubleSpinBox *SpanInput_2;
    QPushButton *zeroButton_2;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLCDNumber *Offset_2;
    QLabel *label_17;
    QLCDNumber *Force_2;
    QPushButton *fZeroButton_2;
    QLCDNumber *Stiffness_2;
    QFrame *line;
    QDoubleSpinBox *approxZero;
    QPushButton *ActOneLowButton;
    QPushButton *ActOneHighButton;
    QTextBrowser *Act1LowOn;
    QTextBrowser *Act1HighOn;
    QTextBrowser *Act2HighOn;
    QTextBrowser *Act2LowOn;
    QPushButton *ActTwoHighButton;
    QPushButton *ActTwoLowButton;
    QCheckBox *SecondActBox;
    QwtPlot *qwtPlot_2;
    QDoubleSpinBox *PInputDisp2;
    QDoubleSpinBox *DInputDisp2;
    QLabel *label_18;
    QLabel *label_19;
    QDoubleSpinBox *IInputDisp2;
    QPushButton *DispPID2;
    QLabel *label_20;
    QFrame *line_2;
    QPushButton *startButton;
    QPushButton *stiffButton;
    QPushButton *saveButton;
    QSpinBox *selectAct;
    QLabel *label_21;
    QCheckBox *InterAct1;
    QPushButton *SwitchControlButton;
    QTextBrowser *ControlText;
    QPushButton *SwitchControlButton_2;
    QTextBrowser *ControlText_2;
    QPushButton *SpanButton_2;
    QDoubleSpinBox *approxZero_2;
    QLabel *label_24;
    QLabel *label_25;
    QDoubleSpinBox *IInputForce;
    QDoubleSpinBox *DInputForce;
    QLabel *label_26;
    QDoubleSpinBox *PInputForce;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QDoubleSpinBox *minDispInput;
    QDoubleSpinBox *maxDispInput;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QFrame *line_3;
    QCheckBox *FirstActBox;
    QFrame *line_4;
    QDoubleSpinBox *IInputForce2;
    QPushButton *ForcePID_2;
    QDoubleSpinBox *PInputForce2;
    QLabel *label_34;
    QLabel *label_35;
    QDoubleSpinBox *DInputForce2;
    QLabel *label_36;
    QLCDNumber *TrueForce;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLCDNumber *TrueForce_2;
    QDoubleSpinBox *Act1ForceScale;
    QDoubleSpinBox *Act1DispScale;
    QDoubleSpinBox *Act2DispScale;
    QDoubleSpinBox *Act2ForceScale;
    QDoubleSpinBox *Act1LCSlope;
    QDoubleSpinBox *Act1MaxLC;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QPushButton *SetPlotScale;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QDoubleSpinBox *Act2LCSlope;
    QDoubleSpinBox *Act2MaxLC;
    QLabel *label_47;
    QLabel *label_48;
    QPushButton *SetLCInfo;
    QLabel *label_49;
    QLabel *label_50;
    QDoubleSpinBox *maxDispInput_2;
    QLabel *label_51;
    QLabel *label_52;
    QDoubleSpinBox *minDispInput_2;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QMenuBar *menuBar;
    QMenu *menuCalibration;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *hsm_full)
    {
        if (hsm_full->objectName().isEmpty())
            hsm_full->setObjectName(QString::fromUtf8("hsm_full"));
        hsm_full->resize(1473, 1021);
        actionCalibration = new QAction(hsm_full);
        actionCalibration->setObjectName(QString::fromUtf8("actionCalibration"));
        actionInterlocks = new QAction(hsm_full);
        actionInterlocks->setObjectName(QString::fromUtf8("actionInterlocks"));
        actionSet_Up_Model = new QAction(hsm_full);
        actionSet_Up_Model->setObjectName(QString::fromUtf8("actionSet_Up_Model"));
        actionPlot_Model = new QAction(hsm_full);
        actionPlot_Model->setObjectName(QString::fromUtf8("actionPlot_Model"));
        centralWidget = new QWidget(hsm_full);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        qwtPlot = new QwtPlot(centralWidget);
        qwtPlot->setObjectName(QString::fromUtf8("qwtPlot"));
        qwtPlot->setGeometry(QRect(20, 20, 611, 311));
        SpanButton = new QPushButton(centralWidget);
        SpanButton->setObjectName(QString::fromUtf8("SpanButton"));
        SpanButton->setEnabled(false);
        SpanButton->setGeometry(QRect(610, 830, 101, 30));
        CurPos = new QLCDNumber(centralWidget);
        CurPos->setObjectName(QString::fromUtf8("CurPos"));
        CurPos->setEnabled(false);
        CurPos->setGeometry(QRect(400, 540, 64, 31));
        Offset = new QLCDNumber(centralWidget);
        Offset->setObjectName(QString::fromUtf8("Offset"));
        Offset->setEnabled(false);
        Offset->setGeometry(QRect(400, 580, 64, 31));
        Offset->setSmallDecimalPoint(false);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setEnabled(false);
        label->setGeometry(QRect(30, 540, 101, 22));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setEnabled(false);
        label_2->setGeometry(QRect(480, 540, 101, 22));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setEnabled(false);
        label_3->setGeometry(QRect(480, 580, 151, 22));
        CurSpan = new QLCDNumber(centralWidget);
        CurSpan->setObjectName(QString::fromUtf8("CurSpan"));
        CurSpan->setEnabled(false);
        CurSpan->setGeometry(QRect(620, 770, 64, 31));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setEnabled(false);
        label_4->setGeometry(QRect(610, 730, 101, 22));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setEnabled(false);
        label_5->setGeometry(QRect(490, 730, 81, 22));
        Force = new QLCDNumber(centralWidget);
        Force->setObjectName(QString::fromUtf8("Force"));
        Force->setEnabled(false);
        Force->setGeometry(QRect(400, 620, 64, 31));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setEnabled(false);
        label_6->setGeometry(QRect(480, 620, 101, 22));
        CommandButton = new QPushButton(centralWidget);
        CommandButton->setObjectName(QString::fromUtf8("CommandButton"));
        CommandButton->setEnabled(false);
        CommandButton->setGeometry(QRect(110, 570, 131, 30));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setEnabled(false);
        label_7->setGeometry(QRect(10, 730, 21, 22));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setEnabled(false);
        label_8->setGeometry(QRect(130, 730, 21, 22));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setEnabled(false);
        label_9->setGeometry(QRect(250, 730, 21, 22));
        ForcePID = new QPushButton(centralWidget);
        ForcePID->setObjectName(QString::fromUtf8("ForcePID"));
        ForcePID->setEnabled(false);
        ForcePID->setGeometry(QRect(150, 870, 61, 30));
        DispPID = new QPushButton(centralWidget);
        DispPID->setObjectName(QString::fromUtf8("DispPID"));
        DispPID->setEnabled(false);
        DispPID->setGeometry(QRect(150, 770, 61, 30));
        CommandInput = new QDoubleSpinBox(centralWidget);
        CommandInput->setObjectName(QString::fromUtf8("CommandInput"));
        CommandInput->setEnabled(false);
        CommandInput->setGeometry(QRect(20, 570, 71, 32));
        CommandInput->setMinimum(-100000000.000000000000000);
        CommandInput->setMaximum(100000000.000000000000000);
        SpanInput = new QDoubleSpinBox(centralWidget);
        SpanInput->setObjectName(QString::fromUtf8("SpanInput"));
        SpanInput->setEnabled(false);
        SpanInput->setGeometry(QRect(490, 770, 81, 32));
        PInputDisp = new QDoubleSpinBox(centralWidget);
        PInputDisp->setObjectName(QString::fromUtf8("PInputDisp"));
        PInputDisp->setEnabled(false);
        PInputDisp->setGeometry(QRect(30, 730, 81, 32));
        IInputDisp = new QDoubleSpinBox(centralWidget);
        IInputDisp->setObjectName(QString::fromUtf8("IInputDisp"));
        IInputDisp->setEnabled(false);
        IInputDisp->setGeometry(QRect(150, 730, 81, 32));
        IInputDisp->setDecimals(10);
        DInputDisp = new QDoubleSpinBox(centralWidget);
        DInputDisp->setObjectName(QString::fromUtf8("DInputDisp"));
        DInputDisp->setEnabled(false);
        DInputDisp->setGeometry(QRect(270, 730, 81, 32));
        zeroButton = new QPushButton(centralWidget);
        zeroButton->setObjectName(QString::fromUtf8("zeroButton"));
        zeroButton->setEnabled(false);
        zeroButton->setGeometry(QRect(598, 540, 111, 30));
        SinButton = new QPushButton(centralWidget);
        SinButton->setObjectName(QString::fromUtf8("SinButton"));
        SinButton->setGeometry(QRect(1140, 380, 91, 30));
        AmpInput = new QDoubleSpinBox(centralWidget);
        AmpInput->setObjectName(QString::fromUtf8("AmpInput"));
        AmpInput->setGeometry(QRect(810, 380, 71, 32));
        FreqInput = new QDoubleSpinBox(centralWidget);
        FreqInput->setObjectName(QString::fromUtf8("FreqInput"));
        FreqInput->setGeometry(QRect(980, 380, 71, 32));
        FreqButton = new QPushButton(centralWidget);
        FreqButton->setObjectName(QString::fromUtf8("FreqButton"));
        FreqButton->setGeometry(QRect(1060, 380, 61, 30));
        AmpButton = new QPushButton(centralWidget);
        AmpButton->setObjectName(QString::fromUtf8("AmpButton"));
        AmpButton->setGeometry(QRect(890, 380, 61, 30));
        SweepButton = new QPushButton(centralWidget);
        SweepButton->setObjectName(QString::fromUtf8("SweepButton"));
        SweepButton->setGeometry(QRect(1250, 380, 91, 30));
        fZeroButton = new QPushButton(centralWidget);
        fZeroButton->setObjectName(QString::fromUtf8("fZeroButton"));
        fZeroButton->setEnabled(false);
        fZeroButton->setGeometry(QRect(598, 620, 111, 30));
        Stiffness = new QLCDNumber(centralWidget);
        Stiffness->setObjectName(QString::fromUtf8("Stiffness"));
        Stiffness->setEnabled(false);
        Stiffness->setGeometry(QRect(400, 660, 64, 31));
        Stiffness->setDigitCount(7);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setEnabled(false);
        label_10->setGeometry(QRect(480, 660, 121, 22));
        AmpTestButton = new QPushButton(centralWidget);
        AmpTestButton->setObjectName(QString::fromUtf8("AmpTestButton"));
        AmpTestButton->setGeometry(QRect(1360, 380, 91, 30));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setEnabled(false);
        label_11->setGeometry(QRect(1240, 580, 151, 22));
        CommandInput_2 = new QDoubleSpinBox(centralWidget);
        CommandInput_2->setObjectName(QString::fromUtf8("CommandInput_2"));
        CommandInput_2->setEnabled(false);
        CommandInput_2->setGeometry(QRect(760, 570, 71, 32));
        CommandInput_2->setMinimum(-100000000.000000000000000);
        CommandInput_2->setMaximum(100000000.000000000000000);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setEnabled(false);
        label_12->setGeometry(QRect(1240, 660, 121, 22));
        CommandButton_2 = new QPushButton(centralWidget);
        CommandButton_2->setObjectName(QString::fromUtf8("CommandButton_2"));
        CommandButton_2->setEnabled(false);
        CommandButton_2->setGeometry(QRect(850, 570, 131, 30));
        CurSpan_2 = new QLCDNumber(centralWidget);
        CurSpan_2->setObjectName(QString::fromUtf8("CurSpan_2"));
        CurSpan_2->setEnabled(false);
        CurSpan_2->setGeometry(QRect(1340, 770, 64, 31));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setEnabled(false);
        label_13->setGeometry(QRect(1330, 730, 101, 22));
        CurPos_2 = new QLCDNumber(centralWidget);
        CurPos_2->setObjectName(QString::fromUtf8("CurPos_2"));
        CurPos_2->setEnabled(false);
        CurPos_2->setGeometry(QRect(1160, 540, 64, 31));
        SpanInput_2 = new QDoubleSpinBox(centralWidget);
        SpanInput_2->setObjectName(QString::fromUtf8("SpanInput_2"));
        SpanInput_2->setEnabled(false);
        SpanInput_2->setGeometry(QRect(1220, 770, 81, 32));
        zeroButton_2 = new QPushButton(centralWidget);
        zeroButton_2->setObjectName(QString::fromUtf8("zeroButton_2"));
        zeroButton_2->setEnabled(false);
        zeroButton_2->setGeometry(QRect(1358, 540, 111, 30));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setEnabled(false);
        label_14->setGeometry(QRect(1240, 540, 111, 22));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setEnabled(false);
        label_15->setGeometry(QRect(770, 540, 101, 22));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(false);
        label_16->setGeometry(QRect(1240, 620, 91, 22));
        Offset_2 = new QLCDNumber(centralWidget);
        Offset_2->setObjectName(QString::fromUtf8("Offset_2"));
        Offset_2->setEnabled(false);
        Offset_2->setGeometry(QRect(1160, 580, 64, 31));
        Offset_2->setSmallDecimalPoint(false);
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setEnabled(false);
        label_17->setGeometry(QRect(1220, 730, 81, 22));
        Force_2 = new QLCDNumber(centralWidget);
        Force_2->setObjectName(QString::fromUtf8("Force_2"));
        Force_2->setEnabled(false);
        Force_2->setGeometry(QRect(1160, 620, 64, 31));
        fZeroButton_2 = new QPushButton(centralWidget);
        fZeroButton_2->setObjectName(QString::fromUtf8("fZeroButton_2"));
        fZeroButton_2->setEnabled(false);
        fZeroButton_2->setGeometry(QRect(1358, 620, 111, 30));
        Stiffness_2 = new QLCDNumber(centralWidget);
        Stiffness_2->setObjectName(QString::fromUtf8("Stiffness_2"));
        Stiffness_2->setEnabled(false);
        Stiffness_2->setGeometry(QRect(1160, 660, 64, 31));
        Stiffness_2->setDigitCount(7);
        line = new QFrame(centralWidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(710, 440, 20, 531));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        approxZero = new QDoubleSpinBox(centralWidget);
        approxZero->setObjectName(QString::fromUtf8("approxZero"));
        approxZero->setEnabled(false);
        approxZero->setGeometry(QRect(490, 830, 81, 32));
        approxZero->setMinimum(-99.000000000000000);
        ActOneLowButton = new QPushButton(centralWidget);
        ActOneLowButton->setObjectName(QString::fromUtf8("ActOneLowButton"));
        ActOneLowButton->setEnabled(false);
        ActOneLowButton->setGeometry(QRect(20, 500, 51, 30));
        ActOneHighButton = new QPushButton(centralWidget);
        ActOneHighButton->setObjectName(QString::fromUtf8("ActOneHighButton"));
        ActOneHighButton->setEnabled(false);
        ActOneHighButton->setGeometry(QRect(170, 500, 51, 30));
        Act1LowOn = new QTextBrowser(centralWidget);
        Act1LowOn->setObjectName(QString::fromUtf8("Act1LowOn"));
        Act1LowOn->setEnabled(false);
        Act1LowOn->setGeometry(QRect(80, 500, 71, 31));
        Act1HighOn = new QTextBrowser(centralWidget);
        Act1HighOn->setObjectName(QString::fromUtf8("Act1HighOn"));
        Act1HighOn->setEnabled(false);
        Act1HighOn->setGeometry(QRect(240, 500, 71, 31));
        Act2HighOn = new QTextBrowser(centralWidget);
        Act2HighOn->setObjectName(QString::fromUtf8("Act2HighOn"));
        Act2HighOn->setEnabled(false);
        Act2HighOn->setGeometry(QRect(970, 500, 71, 31));
        Act2LowOn = new QTextBrowser(centralWidget);
        Act2LowOn->setObjectName(QString::fromUtf8("Act2LowOn"));
        Act2LowOn->setEnabled(false);
        Act2LowOn->setGeometry(QRect(810, 500, 71, 31));
        ActTwoHighButton = new QPushButton(centralWidget);
        ActTwoHighButton->setObjectName(QString::fromUtf8("ActTwoHighButton"));
        ActTwoHighButton->setEnabled(false);
        ActTwoHighButton->setGeometry(QRect(900, 500, 51, 30));
        ActTwoLowButton = new QPushButton(centralWidget);
        ActTwoLowButton->setObjectName(QString::fromUtf8("ActTwoLowButton"));
        ActTwoLowButton->setEnabled(false);
        ActTwoLowButton->setGeometry(QRect(750, 500, 51, 30));
        SecondActBox = new QCheckBox(centralWidget);
        SecondActBox->setObjectName(QString::fromUtf8("SecondActBox"));
        SecondActBox->setGeometry(QRect(750, 450, 111, 21));
        qwtPlot_2 = new QwtPlot(centralWidget);
        qwtPlot_2->setObjectName(QString::fromUtf8("qwtPlot_2"));
        qwtPlot_2->setGeometry(QRect(880, 20, 571, 321));
        PInputDisp2 = new QDoubleSpinBox(centralWidget);
        PInputDisp2->setObjectName(QString::fromUtf8("PInputDisp2"));
        PInputDisp2->setEnabled(false);
        PInputDisp2->setGeometry(QRect(760, 720, 81, 32));
        DInputDisp2 = new QDoubleSpinBox(centralWidget);
        DInputDisp2->setObjectName(QString::fromUtf8("DInputDisp2"));
        DInputDisp2->setEnabled(false);
        DInputDisp2->setGeometry(QRect(1000, 720, 81, 32));
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setEnabled(false);
        label_18->setGeometry(QRect(990, 720, 21, 22));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setEnabled(false);
        label_19->setGeometry(QRect(740, 720, 21, 22));
        IInputDisp2 = new QDoubleSpinBox(centralWidget);
        IInputDisp2->setObjectName(QString::fromUtf8("IInputDisp2"));
        IInputDisp2->setEnabled(false);
        IInputDisp2->setGeometry(QRect(880, 720, 81, 32));
        IInputDisp2->setDecimals(10);
        DispPID2 = new QPushButton(centralWidget);
        DispPID2->setObjectName(QString::fromUtf8("DispPID2"));
        DispPID2->setEnabled(false);
        DispPID2->setGeometry(QRect(890, 760, 61, 30));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setEnabled(false);
        label_20->setGeometry(QRect(870, 720, 21, 22));
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setEnabled(false);
        line_2->setGeometry(QRect(0, 430, 1471, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        startButton = new QPushButton(centralWidget);
        startButton->setObjectName(QString::fromUtf8("startButton"));
        startButton->setGeometry(QRect(150, 380, 121, 31));
        stiffButton = new QPushButton(centralWidget);
        stiffButton->setObjectName(QString::fromUtf8("stiffButton"));
        stiffButton->setGeometry(QRect(640, 380, 141, 31));
        saveButton = new QPushButton(centralWidget);
        saveButton->setObjectName(QString::fromUtf8("saveButton"));
        saveButton->setGeometry(QRect(300, 380, 141, 31));
        selectAct = new QSpinBox(centralWidget);
        selectAct->setObjectName(QString::fromUtf8("selectAct"));
        selectAct->setGeometry(QRect(550, 380, 61, 31));
        selectAct->setMinimum(1);
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(530, 350, 101, 22));
        InterAct1 = new QCheckBox(centralWidget);
        InterAct1->setObjectName(QString::fromUtf8("InterAct1"));
        InterAct1->setGeometry(QRect(20, 350, 121, 21));
        SwitchControlButton = new QPushButton(centralWidget);
        SwitchControlButton->setObjectName(QString::fromUtf8("SwitchControlButton"));
        SwitchControlButton->setEnabled(false);
        SwitchControlButton->setGeometry(QRect(540, 500, 171, 30));
        ControlText = new QTextBrowser(centralWidget);
        ControlText->setObjectName(QString::fromUtf8("ControlText"));
        ControlText->setEnabled(false);
        ControlText->setGeometry(QRect(400, 500, 121, 31));
        SwitchControlButton_2 = new QPushButton(centralWidget);
        SwitchControlButton_2->setObjectName(QString::fromUtf8("SwitchControlButton_2"));
        SwitchControlButton_2->setEnabled(false);
        SwitchControlButton_2->setGeometry(QRect(1300, 500, 171, 30));
        ControlText_2 = new QTextBrowser(centralWidget);
        ControlText_2->setObjectName(QString::fromUtf8("ControlText_2"));
        ControlText_2->setEnabled(false);
        ControlText_2->setGeometry(QRect(1160, 500, 121, 31));
        SpanButton_2 = new QPushButton(centralWidget);
        SpanButton_2->setObjectName(QString::fromUtf8("SpanButton_2"));
        SpanButton_2->setEnabled(false);
        SpanButton_2->setGeometry(QRect(1330, 830, 101, 30));
        approxZero_2 = new QDoubleSpinBox(centralWidget);
        approxZero_2->setObjectName(QString::fromUtf8("approxZero_2"));
        approxZero_2->setEnabled(false);
        approxZero_2->setGeometry(QRect(1220, 830, 81, 32));
        approxZero_2->setMinimum(-99.000000000000000);
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setEnabled(false);
        label_24->setGeometry(QRect(130, 830, 21, 22));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setEnabled(false);
        label_25->setGeometry(QRect(10, 830, 21, 22));
        IInputForce = new QDoubleSpinBox(centralWidget);
        IInputForce->setObjectName(QString::fromUtf8("IInputForce"));
        IInputForce->setEnabled(false);
        IInputForce->setGeometry(QRect(150, 830, 81, 32));
        IInputForce->setDecimals(10);
        DInputForce = new QDoubleSpinBox(centralWidget);
        DInputForce->setObjectName(QString::fromUtf8("DInputForce"));
        DInputForce->setEnabled(false);
        DInputForce->setGeometry(QRect(270, 830, 81, 32));
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setEnabled(false);
        label_26->setGeometry(QRect(250, 830, 21, 22));
        PInputForce = new QDoubleSpinBox(centralWidget);
        PInputForce->setObjectName(QString::fromUtf8("PInputForce"));
        PInputForce->setEnabled(false);
        PInputForce->setGeometry(QRect(30, 830, 81, 32));
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setEnabled(false);
        label_27->setGeometry(QRect(410, 770, 71, 22));
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setEnabled(false);
        label_28->setGeometry(QRect(410, 830, 71, 22));
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setEnabled(false);
        label_29->setGeometry(QRect(380, 850, 101, 22));
        minDispInput = new QDoubleSpinBox(centralWidget);
        minDispInput->setObjectName(QString::fromUtf8("minDispInput"));
        minDispInput->setEnabled(false);
        minDispInput->setGeometry(QRect(430, 450, 81, 32));
        minDispInput->setMinimum(-1000.000000000000000);
        minDispInput->setMaximum(1000.000000000000000);
        maxDispInput = new QDoubleSpinBox(centralWidget);
        maxDispInput->setObjectName(QString::fromUtf8("maxDispInput"));
        maxDispInput->setEnabled(false);
        maxDispInput->setGeometry(QRect(630, 450, 81, 32));
        maxDispInput->setMinimum(-1000.000000000000000);
        maxDispInput->setMaximum(1000.000000000000000);
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setEnabled(false);
        label_30->setGeometry(QRect(350, 440, 51, 22));
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setEnabled(false);
        label_31->setGeometry(QRect(320, 460, 111, 22));
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setEnabled(false);
        label_32->setGeometry(QRect(520, 460, 111, 22));
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setEnabled(false);
        label_33->setGeometry(QRect(550, 440, 51, 22));
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(0, 700, 781, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        FirstActBox = new QCheckBox(centralWidget);
        FirstActBox->setObjectName(QString::fromUtf8("FirstActBox"));
        FirstActBox->setEnabled(true);
        FirstActBox->setGeometry(QRect(20, 450, 111, 21));
        FirstActBox->setChecked(false);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(780, 700, 781, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        IInputForce2 = new QDoubleSpinBox(centralWidget);
        IInputForce2->setObjectName(QString::fromUtf8("IInputForce2"));
        IInputForce2->setEnabled(false);
        IInputForce2->setGeometry(QRect(880, 830, 81, 32));
        IInputForce2->setDecimals(10);
        ForcePID_2 = new QPushButton(centralWidget);
        ForcePID_2->setObjectName(QString::fromUtf8("ForcePID_2"));
        ForcePID_2->setEnabled(false);
        ForcePID_2->setGeometry(QRect(890, 870, 61, 30));
        PInputForce2 = new QDoubleSpinBox(centralWidget);
        PInputForce2->setObjectName(QString::fromUtf8("PInputForce2"));
        PInputForce2->setEnabled(false);
        PInputForce2->setGeometry(QRect(760, 830, 81, 32));
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setEnabled(false);
        label_34->setGeometry(QRect(740, 830, 21, 22));
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setEnabled(false);
        label_35->setGeometry(QRect(980, 830, 21, 22));
        DInputForce2 = new QDoubleSpinBox(centralWidget);
        DInputForce2->setObjectName(QString::fromUtf8("DInputForce2"));
        DInputForce2->setEnabled(false);
        DInputForce2->setGeometry(QRect(1000, 830, 81, 32));
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setEnabled(false);
        label_36->setGeometry(QRect(860, 830, 21, 22));
        TrueForce = new QLCDNumber(centralWidget);
        TrueForce->setObjectName(QString::fromUtf8("TrueForce"));
        TrueForce->setEnabled(false);
        TrueForce->setGeometry(QRect(320, 620, 64, 31));
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setEnabled(false);
        label_37->setGeometry(QRect(310, 570, 121, 22));
        label_38 = new QLabel(centralWidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setEnabled(false);
        label_38->setGeometry(QRect(310, 590, 121, 22));
        label_39 = new QLabel(centralWidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setEnabled(false);
        label_39->setGeometry(QRect(1080, 570, 121, 22));
        label_40 = new QLabel(centralWidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setEnabled(false);
        label_40->setGeometry(QRect(1080, 590, 121, 22));
        TrueForce_2 = new QLCDNumber(centralWidget);
        TrueForce_2->setObjectName(QString::fromUtf8("TrueForce_2"));
        TrueForce_2->setEnabled(false);
        TrueForce_2->setGeometry(QRect(1090, 620, 64, 31));
        Act1ForceScale = new QDoubleSpinBox(centralWidget);
        Act1ForceScale->setObjectName(QString::fromUtf8("Act1ForceScale"));
        Act1ForceScale->setGeometry(QRect(790, 50, 71, 32));
        Act1ForceScale->setValue(1.000000000000000);
        Act1DispScale = new QDoubleSpinBox(centralWidget);
        Act1DispScale->setObjectName(QString::fromUtf8("Act1DispScale"));
        Act1DispScale->setGeometry(QRect(690, 50, 71, 32));
        Act1DispScale->setValue(1.000000000000000);
        Act2DispScale = new QDoubleSpinBox(centralWidget);
        Act2DispScale->setObjectName(QString::fromUtf8("Act2DispScale"));
        Act2DispScale->setGeometry(QRect(690, 100, 71, 32));
        Act2DispScale->setValue(1.000000000000000);
        Act2ForceScale = new QDoubleSpinBox(centralWidget);
        Act2ForceScale->setObjectName(QString::fromUtf8("Act2ForceScale"));
        Act2ForceScale->setGeometry(QRect(790, 100, 71, 32));
        Act2ForceScale->setValue(1.000000000000000);
        Act1LCSlope = new QDoubleSpinBox(centralWidget);
        Act1LCSlope->setObjectName(QString::fromUtf8("Act1LCSlope"));
        Act1LCSlope->setGeometry(QRect(790, 230, 71, 32));
        Act1LCSlope->setDecimals(8);
        Act1LCSlope->setMinimum(-100.000000000000000);
        Act1LCSlope->setMaximum(100.000000000000000);
        Act1MaxLC = new QDoubleSpinBox(centralWidget);
        Act1MaxLC->setObjectName(QString::fromUtf8("Act1MaxLC"));
        Act1MaxLC->setGeometry(QRect(690, 230, 71, 32));
        Act1MaxLC->setMaximum(10000000.000000000000000);
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(700, 0, 131, 22));
        QFont font;
        font.setPointSize(14);
        label_22->setFont(font);
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(640, 50, 41, 22));
        label_41 = new QLabel(centralWidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(640, 100, 41, 21));
        label_42 = new QLabel(centralWidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(700, 20, 101, 22));
        label_43 = new QLabel(centralWidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(790, 20, 101, 22));
        SetPlotScale = new QPushButton(centralWidget);
        SetPlotScale->setObjectName(QString::fromUtf8("SetPlotScale"));
        SetPlotScale->setGeometry(QRect(710, 140, 101, 30));
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(730, 180, 101, 22));
        label_44->setFont(font);
        label_45 = new QLabel(centralWidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(640, 230, 31, 22));
        label_46 = new QLabel(centralWidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(640, 270, 31, 22));
        Act2LCSlope = new QDoubleSpinBox(centralWidget);
        Act2LCSlope->setObjectName(QString::fromUtf8("Act2LCSlope"));
        Act2LCSlope->setGeometry(QRect(790, 270, 71, 32));
        Act2LCSlope->setDecimals(8);
        Act2LCSlope->setMinimum(-100.000000000000000);
        Act2LCSlope->setMaximum(100.000000000000000);
        Act2MaxLC = new QDoubleSpinBox(centralWidget);
        Act2MaxLC->setObjectName(QString::fromUtf8("Act2MaxLC"));
        Act2MaxLC->setGeometry(QRect(690, 270, 71, 32));
        Act2MaxLC->setMaximum(10000000.000000000000000);
        label_47 = new QLabel(centralWidget);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(700, 200, 101, 22));
        label_48 = new QLabel(centralWidget);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(790, 200, 101, 22));
        SetLCInfo = new QPushButton(centralWidget);
        SetLCInfo->setObjectName(QString::fromUtf8("SetLCInfo"));
        SetLCInfo->setGeometry(QRect(710, 310, 101, 30));
        label_49 = new QLabel(centralWidget);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setEnabled(false);
        label_49->setGeometry(QRect(1310, 440, 51, 22));
        label_50 = new QLabel(centralWidget);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setEnabled(false);
        label_50->setGeometry(QRect(1280, 460, 111, 22));
        maxDispInput_2 = new QDoubleSpinBox(centralWidget);
        maxDispInput_2->setObjectName(QString::fromUtf8("maxDispInput_2"));
        maxDispInput_2->setEnabled(false);
        maxDispInput_2->setGeometry(QRect(1390, 450, 81, 32));
        maxDispInput_2->setMinimum(-1000.000000000000000);
        maxDispInput_2->setMaximum(1000.000000000000000);
        label_51 = new QLabel(centralWidget);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setEnabled(false);
        label_51->setGeometry(QRect(1080, 460, 111, 22));
        label_52 = new QLabel(centralWidget);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setEnabled(false);
        label_52->setGeometry(QRect(1110, 440, 51, 22));
        minDispInput_2 = new QDoubleSpinBox(centralWidget);
        minDispInput_2->setObjectName(QString::fromUtf8("minDispInput_2"));
        minDispInput_2->setEnabled(false);
        minDispInput_2->setGeometry(QRect(1190, 450, 81, 32));
        minDispInput_2->setMinimum(-1000.000000000000000);
        minDispInput_2->setMaximum(1000.000000000000000);
        label_53 = new QLabel(centralWidget);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setEnabled(false);
        label_53->setGeometry(QRect(1140, 770, 71, 22));
        label_54 = new QLabel(centralWidget);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setEnabled(false);
        label_54->setGeometry(QRect(1110, 850, 101, 22));
        label_55 = new QLabel(centralWidget);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setEnabled(false);
        label_55->setGeometry(QRect(1140, 830, 71, 22));
        hsm_full->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(hsm_full);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1473, 20));
        menuCalibration = new QMenu(menuBar);
        menuCalibration->setObjectName(QString::fromUtf8("menuCalibration"));
        hsm_full->setMenuBar(menuBar);
        mainToolBar = new QToolBar(hsm_full);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        hsm_full->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(hsm_full);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        hsm_full->setStatusBar(statusBar);

        menuBar->addAction(menuCalibration->menuAction());
        menuCalibration->addAction(actionCalibration);
        menuCalibration->addAction(actionInterlocks);
        menuCalibration->addAction(actionSet_Up_Model);
        menuCalibration->addAction(actionPlot_Model);

        retranslateUi(hsm_full);

        QMetaObject::connectSlotsByName(hsm_full);
    } // setupUi

    void retranslateUi(QMainWindow *hsm_full)
    {
        hsm_full->setWindowTitle(QCoreApplication::translate("hsm_full", "hsm_full", nullptr));
        actionCalibration->setText(QCoreApplication::translate("hsm_full", "Calibration", nullptr));
        actionInterlocks->setText(QCoreApplication::translate("hsm_full", "Interlocks", nullptr));
        actionSet_Up_Model->setText(QCoreApplication::translate("hsm_full", "Set Up Model", nullptr));
        actionPlot_Model->setText(QCoreApplication::translate("hsm_full", "Plot HSM Results", nullptr));
        SpanButton->setText(QCoreApplication::translate("hsm_full", "Set Span", nullptr));
        label->setText(QCoreApplication::translate("hsm_full", "Command", nullptr));
        label_2->setText(QCoreApplication::translate("hsm_full", "Current Position", nullptr));
        label_3->setText(QCoreApplication::translate("hsm_full", "Offset from Zero", nullptr));
        label_4->setText(QCoreApplication::translate("hsm_full", "Current Span:", nullptr));
        label_5->setText(QCoreApplication::translate("hsm_full", "Input Span:", nullptr));
        label_6->setText(QCoreApplication::translate("hsm_full", "Force Reading", nullptr));
        CommandButton->setText(QCoreApplication::translate("hsm_full", "Send Command", nullptr));
        label_7->setText(QCoreApplication::translate("hsm_full", "P", nullptr));
        label_8->setText(QCoreApplication::translate("hsm_full", "I", nullptr));
        label_9->setText(QCoreApplication::translate("hsm_full", "D", nullptr));
        ForcePID->setText(QCoreApplication::translate("hsm_full", "Set", nullptr));
        DispPID->setText(QCoreApplication::translate("hsm_full", "Set", nullptr));
        zeroButton->setText(QCoreApplication::translate("hsm_full", "Set Zero", nullptr));
        SinButton->setText(QCoreApplication::translate("hsm_full", "Sin Test", nullptr));
        FreqButton->setText(QCoreApplication::translate("hsm_full", "Set Freq", nullptr));
        AmpButton->setText(QCoreApplication::translate("hsm_full", "Set Amp", nullptr));
        SweepButton->setText(QCoreApplication::translate("hsm_full", "Sweep", nullptr));
        fZeroButton->setText(QCoreApplication::translate("hsm_full", "Calibrate Force", nullptr));
        label_10->setText(QCoreApplication::translate("hsm_full", "Approx Stiffness", nullptr));
        AmpTestButton->setText(QCoreApplication::translate("hsm_full", "Amp Test", nullptr));
        label_11->setText(QCoreApplication::translate("hsm_full", "Offset from Zero", nullptr));
        label_12->setText(QCoreApplication::translate("hsm_full", "Approx Stiffness", nullptr));
        CommandButton_2->setText(QCoreApplication::translate("hsm_full", "Send Command", nullptr));
        label_13->setText(QCoreApplication::translate("hsm_full", "Current Span:", nullptr));
        zeroButton_2->setText(QCoreApplication::translate("hsm_full", "Set Zero", nullptr));
        label_14->setText(QCoreApplication::translate("hsm_full", "Current Position", nullptr));
        label_15->setText(QCoreApplication::translate("hsm_full", "Command", nullptr));
        label_16->setText(QCoreApplication::translate("hsm_full", "Force Reading", nullptr));
        label_17->setText(QCoreApplication::translate("hsm_full", "Input Span:", nullptr));
        fZeroButton_2->setText(QCoreApplication::translate("hsm_full", "Calibrate Force", nullptr));
        ActOneLowButton->setText(QCoreApplication::translate("hsm_full", "Low ", nullptr));
        ActOneHighButton->setText(QCoreApplication::translate("hsm_full", "High", nullptr));
        ActTwoHighButton->setText(QCoreApplication::translate("hsm_full", "High", nullptr));
        ActTwoLowButton->setText(QCoreApplication::translate("hsm_full", "Low ", nullptr));
        SecondActBox->setText(QCoreApplication::translate("hsm_full", "Use Actuator 2", nullptr));
        label_18->setText(QCoreApplication::translate("hsm_full", "D", nullptr));
        label_19->setText(QCoreApplication::translate("hsm_full", "P", nullptr));
        DispPID2->setText(QCoreApplication::translate("hsm_full", "Set", nullptr));
        label_20->setText(QCoreApplication::translate("hsm_full", "I", nullptr));
        startButton->setText(QCoreApplication::translate("hsm_full", "Run HSM", nullptr));
        stiffButton->setText(QCoreApplication::translate("hsm_full", "Run Stiffness Test", nullptr));
        saveButton->setText(QCoreApplication::translate("hsm_full", "Save All Data", nullptr));
        label_21->setText(QCoreApplication::translate("hsm_full", "Actuator Select", nullptr));
        InterAct1->setText(QCoreApplication::translate("hsm_full", "Interlocks On", nullptr));
        SwitchControlButton->setText(QCoreApplication::translate("hsm_full", "Switch to Force Control", nullptr));
        SwitchControlButton_2->setText(QCoreApplication::translate("hsm_full", "Switch to Force Control", nullptr));
        SpanButton_2->setText(QCoreApplication::translate("hsm_full", "Set Span", nullptr));
        label_24->setText(QCoreApplication::translate("hsm_full", "I", nullptr));
        label_25->setText(QCoreApplication::translate("hsm_full", "P", nullptr));
        label_26->setText(QCoreApplication::translate("hsm_full", "D", nullptr));
        label_27->setText(QCoreApplication::translate("hsm_full", "Span Input", nullptr));
        label_28->setText(QCoreApplication::translate("hsm_full", "Zero Point", nullptr));
        label_29->setText(QCoreApplication::translate("hsm_full", "(zero-max span)", nullptr));
        label_30->setText(QCoreApplication::translate("hsm_full", "Min Pos ", nullptr));
        label_31->setText(QCoreApplication::translate("hsm_full", "For Force Control", nullptr));
        label_32->setText(QCoreApplication::translate("hsm_full", "For Force Control", nullptr));
        label_33->setText(QCoreApplication::translate("hsm_full", "Max Pos ", nullptr));
        FirstActBox->setText(QCoreApplication::translate("hsm_full", "Use  Actuator 1", nullptr));
        ForcePID_2->setText(QCoreApplication::translate("hsm_full", "Set", nullptr));
        label_34->setText(QCoreApplication::translate("hsm_full", "P", nullptr));
        label_35->setText(QCoreApplication::translate("hsm_full", "D", nullptr));
        label_36->setText(QCoreApplication::translate("hsm_full", "I", nullptr));
        label_37->setText(QCoreApplication::translate("hsm_full", "True Reading", nullptr));
        label_38->setText(QCoreApplication::translate("hsm_full", "(without zero)", nullptr));
        label_39->setText(QCoreApplication::translate("hsm_full", "True Reading", nullptr));
        label_40->setText(QCoreApplication::translate("hsm_full", "(without zero)", nullptr));
        label_22->setText(QCoreApplication::translate("hsm_full", "Plotting Scale", nullptr));
        label_23->setText(QCoreApplication::translate("hsm_full", "Act 1", nullptr));
        label_41->setText(QCoreApplication::translate("hsm_full", "Act 2", nullptr));
        label_42->setText(QCoreApplication::translate("hsm_full", "Disp", nullptr));
        label_43->setText(QCoreApplication::translate("hsm_full", "Force", nullptr));
        SetPlotScale->setText(QCoreApplication::translate("hsm_full", "Set Scales", nullptr));
        label_44->setText(QCoreApplication::translate("hsm_full", "LC Info", nullptr));
        label_45->setText(QCoreApplication::translate("hsm_full", "Act 1", nullptr));
        label_46->setText(QCoreApplication::translate("hsm_full", "Act 2", nullptr));
        label_47->setText(QCoreApplication::translate("hsm_full", "Max Load", nullptr));
        label_48->setText(QCoreApplication::translate("hsm_full", "Slope", nullptr));
        SetLCInfo->setText(QCoreApplication::translate("hsm_full", "Set Load Cells", nullptr));
        label_49->setText(QCoreApplication::translate("hsm_full", "Max Pos ", nullptr));
        label_50->setText(QCoreApplication::translate("hsm_full", "For Force Control", nullptr));
        label_51->setText(QCoreApplication::translate("hsm_full", "For Force Control", nullptr));
        label_52->setText(QCoreApplication::translate("hsm_full", "Min Pos ", nullptr));
        label_53->setText(QCoreApplication::translate("hsm_full", "Span Input", nullptr));
        label_54->setText(QCoreApplication::translate("hsm_full", "(zero-max span)", nullptr));
        label_55->setText(QCoreApplication::translate("hsm_full", "Zero Point", nullptr));
        menuCalibration->setTitle(QCoreApplication::translate("hsm_full", "Options", nullptr));
    } // retranslateUi

};

namespace Ui {
    class hsm_full: public Ui_hsm_full {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HSM_FULL_H
