/********************************************************************************
** Form generated from reading UI file 'psas.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PSAS_H
#define UI_PSAS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_PSAS
{
public:
    QAction *actionGround_Motion;
    QWidget *centralwidget;
    QDoubleSpinBox *x_pos_input;
    QDoubleSpinBox *y_pos_input;
    QDoubleSpinBox *z_pos_input;
    QPushButton *add_node;
    QPushButton *remove_node;
    QTextEdit *textEdit;
    QSpinBox *i_node_input;
    QSpinBox *j_node_input;
    QPushButton *add_element_button;
    QTextEdit *textEdit_2;
    QTextEdit *textEdit_3;
    QDoubleSpinBox *E_input;
    QDoubleSpinBox *A_input;
    QDoubleSpinBox *J_input;
    QDoubleSpinBox *v_input;
    QDoubleSpinBox *Iy_input;
    QDoubleSpinBox *Iz_input;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QPushButton *El_prop_button;
    QSpinBox *El_Prop_select;
    QLabel *label_7;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QSpinBox *BC_Node;
    QLabel *label_8;
    QSpinBox *Bx_input;
    QSpinBox *By_input;
    QSpinBox *Bz_input;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QSpinBox *Bry_input;
    QLabel *label_18;
    QSpinBox *Brx_input;
    QSpinBox *Brz_input;
    QLabel *label_19;
    QTextEdit *textEdit_4;
    QSpinBox *Element_load_select;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QTextEdit *textEdit_5;
    QLabel *label_26;
    QSpinBox *Node_Load_Select;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QTextEdit *textEdit_6;
    QLabel *label_32;
    QLabel *label_33;
    QPushButton *remove_element_button;
    QPushButton *Boundary_Button;
    QPushButton *El_Load_Button;
    QPushButton *Nodal_Load_Button;
    QDoubleSpinBox *wz_input;
    QDoubleSpinBox *rx_input;
    QDoubleSpinBox *wx_input;
    QDoubleSpinBox *wy_input;
    QDoubleSpinBox *ry_input;
    QDoubleSpinBox *rz_input;
    QDoubleSpinBox *zLoad_input;
    QDoubleSpinBox *mxLoad_input;
    QDoubleSpinBox *xLoad_input;
    QDoubleSpinBox *yLoad_input;
    QDoubleSpinBox *myLoad_input;
    QDoubleSpinBox *mzLoad_input;
    QPushButton *SubmitModel;
    QCheckBox *HybridCheck;
    QPushButton *SwitchDimButton;
    QTextEdit *DimText;
    QDoubleSpinBox *Mass_Input;
    QLabel *label_34;
    QCheckBox *selfWeightCheck;
    QLabel *label_35;
    QDoubleSpinBox *rho_input;
    QPushButton *plotModelButton;
    QPushButton *HybridProps;
    QPushButton *submitEQ;
    QPlainTextEdit *plainTextEdit;
    QDoubleSpinBox *scale;
    QDoubleSpinBox *dtold;
    QDoubleSpinBox *dt;
    QDoubleSpinBox *alpha;
    QDoubleSpinBox *zeta;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QPushButton *submitDynOp;
    QPlainTextEdit *plainTextEdit_2;
    QDoubleSpinBox *dir1;
    QDoubleSpinBox *dir2;
    QDoubleSpinBox *dir3;
    QDoubleSpinBox *Mode1;
    QDoubleSpinBox *Mode2;
    QDoubleSpinBox *REL1;
    QDoubleSpinBox *REL2;
    QDoubleSpinBox *REL3;
    QDoubleSpinBox *REL7;
    QDoubleSpinBox *REL8;
    QDoubleSpinBox *REL9;
    QDoubleSpinBox *REL4;
    QDoubleSpinBox *REL5;
    QDoubleSpinBox *REL6;
    QDoubleSpinBox *REL10;
    QDoubleSpinBox *REL11;
    QDoubleSpinBox *REL12;
    QTextEdit *ElREL;
    QLabel *label_47;
    QPushButton *CustomEl;
    QCheckBox *CustomCheck;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QLabel *label_48;
    QLabel *label_49;
    QDoubleSpinBox *HybridDof1;
    QDoubleSpinBox *HybridDof2;
    QPlainTextEdit *ModelDisplay;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QPushButton *pickActuators;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *PSAS)
    {
        if (PSAS->objectName().isEmpty())
            PSAS->setObjectName(QString::fromUtf8("PSAS"));
        PSAS->resize(1325, 843);
        actionGround_Motion = new QAction(PSAS);
        actionGround_Motion->setObjectName(QString::fromUtf8("actionGround_Motion"));
        centralwidget = new QWidget(PSAS);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        x_pos_input = new QDoubleSpinBox(centralwidget);
        x_pos_input->setObjectName(QString::fromUtf8("x_pos_input"));
        x_pos_input->setGeometry(QRect(20, 80, 67, 31));
        y_pos_input = new QDoubleSpinBox(centralwidget);
        y_pos_input->setObjectName(QString::fromUtf8("y_pos_input"));
        y_pos_input->setGeometry(QRect(100, 80, 67, 31));
        z_pos_input = new QDoubleSpinBox(centralwidget);
        z_pos_input->setObjectName(QString::fromUtf8("z_pos_input"));
        z_pos_input->setEnabled(false);
        z_pos_input->setGeometry(QRect(180, 80, 67, 31));
        add_node = new QPushButton(centralwidget);
        add_node->setObjectName(QString::fromUtf8("add_node"));
        add_node->setGeometry(QRect(20, 180, 91, 30));
        remove_node = new QPushButton(centralwidget);
        remove_node->setObjectName(QString::fromUtf8("remove_node"));
        remove_node->setGeometry(QRect(130, 180, 111, 30));
        textEdit = new QTextEdit(centralwidget);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(270, 70, 201, 121));
        i_node_input = new QSpinBox(centralwidget);
        i_node_input->setObjectName(QString::fromUtf8("i_node_input"));
        i_node_input->setGeometry(QRect(20, 250, 46, 31));
        j_node_input = new QSpinBox(centralwidget);
        j_node_input->setObjectName(QString::fromUtf8("j_node_input"));
        j_node_input->setGeometry(QRect(80, 250, 46, 31));
        add_element_button = new QPushButton(centralwidget);
        add_element_button->setObjectName(QString::fromUtf8("add_element_button"));
        add_element_button->setGeometry(QRect(150, 250, 101, 30));
        textEdit_2 = new QTextEdit(centralwidget);
        textEdit_2->setObjectName(QString::fromUtf8("textEdit_2"));
        textEdit_2->setGeometry(QRect(270, 230, 201, 91));
        textEdit_3 = new QTextEdit(centralwidget);
        textEdit_3->setObjectName(QString::fromUtf8("textEdit_3"));
        textEdit_3->setGeometry(QRect(270, 340, 201, 261));
        E_input = new QDoubleSpinBox(centralwidget);
        E_input->setObjectName(QString::fromUtf8("E_input"));
        E_input->setGeometry(QRect(20, 400, 67, 31));
        E_input->setDecimals(10);
        E_input->setMaximum(1000000.000000000000000);
        A_input = new QDoubleSpinBox(centralwidget);
        A_input->setObjectName(QString::fromUtf8("A_input"));
        A_input->setGeometry(QRect(100, 400, 67, 31));
        A_input->setDecimals(5);
        A_input->setMaximum(10000000000000000303786028427003666890752.000000000000000);
        J_input = new QDoubleSpinBox(centralwidget);
        J_input->setObjectName(QString::fromUtf8("J_input"));
        J_input->setEnabled(false);
        J_input->setGeometry(QRect(180, 400, 67, 31));
        J_input->setDecimals(5);
        J_input->setMaximum(1000000.000000000000000);
        v_input = new QDoubleSpinBox(centralwidget);
        v_input->setObjectName(QString::fromUtf8("v_input"));
        v_input->setEnabled(false);
        v_input->setGeometry(QRect(20, 460, 67, 31));
        v_input->setDecimals(10);
        v_input->setMaximum(1000000.000000000000000);
        Iy_input = new QDoubleSpinBox(centralwidget);
        Iy_input->setObjectName(QString::fromUtf8("Iy_input"));
        Iy_input->setEnabled(false);
        Iy_input->setGeometry(QRect(100, 460, 67, 31));
        Iy_input->setDecimals(10);
        Iy_input->setMaximum(1000000.000000000000000);
        Iz_input = new QDoubleSpinBox(centralwidget);
        Iz_input->setObjectName(QString::fromUtf8("Iz_input"));
        Iz_input->setGeometry(QRect(180, 460, 67, 31));
        Iz_input->setDecimals(10);
        Iz_input->setMaximum(1000000.000000000000000);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(40, 380, 16, 22));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(120, 380, 16, 22));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(200, 380, 16, 22));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(40, 440, 16, 22));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(120, 440, 16, 22));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(200, 440, 16, 22));
        El_prop_button = new QPushButton(centralwidget);
        El_prop_button->setObjectName(QString::fromUtf8("El_prop_button"));
        El_prop_button->setGeometry(QRect(20, 720, 141, 30));
        El_Prop_select = new QSpinBox(centralwidget);
        El_Prop_select->setObjectName(QString::fromUtf8("El_Prop_select"));
        El_Prop_select->setGeometry(QRect(90, 340, 46, 31));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 340, 71, 22));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 230, 61, 22));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(80, 230, 51, 22));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 60, 61, 22));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(110, 60, 61, 22));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(190, 60, 61, 22));
        BC_Node = new QSpinBox(centralwidget);
        BC_Node->setObjectName(QString::fromUtf8("BC_Node"));
        BC_Node->setGeometry(QRect(580, 40, 46, 31));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(510, 40, 71, 22));
        Bx_input = new QSpinBox(centralwidget);
        Bx_input->setObjectName(QString::fromUtf8("Bx_input"));
        Bx_input->setGeometry(QRect(510, 90, 46, 31));
        By_input = new QSpinBox(centralwidget);
        By_input->setObjectName(QString::fromUtf8("By_input"));
        By_input->setGeometry(QRect(570, 90, 46, 31));
        Bz_input = new QSpinBox(centralwidget);
        Bz_input->setObjectName(QString::fromUtf8("Bz_input"));
        Bz_input->setEnabled(false);
        Bz_input->setGeometry(QRect(630, 90, 46, 31));
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(640, 70, 21, 22));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(520, 70, 21, 22));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(580, 70, 21, 22));
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(640, 130, 31, 22));
        Bry_input = new QSpinBox(centralwidget);
        Bry_input->setObjectName(QString::fromUtf8("Bry_input"));
        Bry_input->setEnabled(false);
        Bry_input->setGeometry(QRect(570, 150, 46, 31));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(520, 130, 31, 22));
        Brx_input = new QSpinBox(centralwidget);
        Brx_input->setObjectName(QString::fromUtf8("Brx_input"));
        Brx_input->setEnabled(false);
        Brx_input->setGeometry(QRect(510, 150, 46, 31));
        Brz_input = new QSpinBox(centralwidget);
        Brz_input->setObjectName(QString::fromUtf8("Brz_input"));
        Brz_input->setGeometry(QRect(630, 150, 46, 31));
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(580, 130, 31, 22));
        textEdit_4 = new QTextEdit(centralwidget);
        textEdit_4->setObjectName(QString::fromUtf8("textEdit_4"));
        textEdit_4->setGeometry(QRect(740, 40, 171, 111));
        Element_load_select = new QSpinBox(centralwidget);
        Element_load_select->setObjectName(QString::fromUtf8("Element_load_select"));
        Element_load_select->setGeometry(QRect(570, 240, 46, 31));
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(680, 270, 21, 22));
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(520, 270, 21, 22));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(600, 330, 31, 22));
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(500, 240, 71, 22));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(680, 330, 31, 22));
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(600, 270, 21, 22));
        textEdit_5 = new QTextEdit(centralwidget);
        textEdit_5->setObjectName(QString::fromUtf8("textEdit_5"));
        textEdit_5->setGeometry(QRect(750, 230, 171, 111));
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(520, 330, 31, 22));
        Node_Load_Select = new QSpinBox(centralwidget);
        Node_Load_Select->setObjectName(QString::fromUtf8("Node_Load_Select"));
        Node_Load_Select->setGeometry(QRect(580, 440, 46, 31));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(500, 470, 71, 22));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(510, 440, 71, 22));
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(670, 470, 61, 22));
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(600, 530, 31, 22));
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(520, 530, 31, 22));
        textEdit_6 = new QTextEdit(centralwidget);
        textEdit_6->setObjectName(QString::fromUtf8("textEdit_6"));
        textEdit_6->setGeometry(QRect(750, 430, 171, 111));
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(680, 530, 31, 22));
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(590, 470, 61, 22));
        remove_element_button = new QPushButton(centralwidget);
        remove_element_button->setObjectName(QString::fromUtf8("remove_element_button"));
        remove_element_button->setGeometry(QRect(150, 290, 101, 30));
        Boundary_Button = new QPushButton(centralwidget);
        Boundary_Button->setObjectName(QString::fromUtf8("Boundary_Button"));
        Boundary_Button->setGeometry(QRect(740, 160, 171, 31));
        El_Load_Button = new QPushButton(centralwidget);
        El_Load_Button->setObjectName(QString::fromUtf8("El_Load_Button"));
        El_Load_Button->setGeometry(QRect(750, 350, 161, 30));
        Nodal_Load_Button = new QPushButton(centralwidget);
        Nodal_Load_Button->setObjectName(QString::fromUtf8("Nodal_Load_Button"));
        Nodal_Load_Button->setGeometry(QRect(750, 550, 161, 30));
        wz_input = new QDoubleSpinBox(centralwidget);
        wz_input->setObjectName(QString::fromUtf8("wz_input"));
        wz_input->setEnabled(false);
        wz_input->setGeometry(QRect(660, 290, 67, 31));
        wz_input->setDecimals(10);
        wz_input->setMinimum(-1000000.000000000000000);
        wz_input->setMaximum(1000000.000000000000000);
        rx_input = new QDoubleSpinBox(centralwidget);
        rx_input->setObjectName(QString::fromUtf8("rx_input"));
        rx_input->setEnabled(false);
        rx_input->setGeometry(QRect(500, 350, 67, 31));
        rx_input->setDecimals(10);
        rx_input->setMinimum(-1000000.000000000000000);
        rx_input->setMaximum(1000000.000000000000000);
        wx_input = new QDoubleSpinBox(centralwidget);
        wx_input->setObjectName(QString::fromUtf8("wx_input"));
        wx_input->setGeometry(QRect(500, 290, 67, 31));
        wx_input->setDecimals(10);
        wx_input->setMinimum(-1000000.000000000000000);
        wx_input->setMaximum(1000000.000000000000000);
        wy_input = new QDoubleSpinBox(centralwidget);
        wy_input->setObjectName(QString::fromUtf8("wy_input"));
        wy_input->setGeometry(QRect(580, 290, 67, 31));
        wy_input->setDecimals(10);
        wy_input->setMinimum(-1000000.000000000000000);
        wy_input->setMaximum(1000000.000000000000000);
        ry_input = new QDoubleSpinBox(centralwidget);
        ry_input->setObjectName(QString::fromUtf8("ry_input"));
        ry_input->setEnabled(false);
        ry_input->setGeometry(QRect(580, 350, 67, 31));
        ry_input->setDecimals(10);
        ry_input->setMinimum(-1000000.000000000000000);
        ry_input->setMaximum(1000000.000000000000000);
        rz_input = new QDoubleSpinBox(centralwidget);
        rz_input->setObjectName(QString::fromUtf8("rz_input"));
        rz_input->setGeometry(QRect(660, 350, 67, 31));
        rz_input->setDecimals(10);
        rz_input->setMinimum(-1000000.000000000000000);
        rz_input->setMaximum(1000000.000000000000000);
        zLoad_input = new QDoubleSpinBox(centralwidget);
        zLoad_input->setObjectName(QString::fromUtf8("zLoad_input"));
        zLoad_input->setEnabled(false);
        zLoad_input->setGeometry(QRect(660, 490, 67, 31));
        zLoad_input->setDecimals(10);
        zLoad_input->setMinimum(-1000000.000000000000000);
        zLoad_input->setMaximum(1000000.000000000000000);
        mxLoad_input = new QDoubleSpinBox(centralwidget);
        mxLoad_input->setObjectName(QString::fromUtf8("mxLoad_input"));
        mxLoad_input->setEnabled(false);
        mxLoad_input->setGeometry(QRect(500, 550, 67, 31));
        mxLoad_input->setDecimals(10);
        mxLoad_input->setMinimum(-1000000.000000000000000);
        mxLoad_input->setMaximum(1000000.000000000000000);
        xLoad_input = new QDoubleSpinBox(centralwidget);
        xLoad_input->setObjectName(QString::fromUtf8("xLoad_input"));
        xLoad_input->setGeometry(QRect(500, 490, 67, 31));
        xLoad_input->setDecimals(10);
        xLoad_input->setMinimum(-1000000.000000000000000);
        xLoad_input->setMaximum(1000000.000000000000000);
        yLoad_input = new QDoubleSpinBox(centralwidget);
        yLoad_input->setObjectName(QString::fromUtf8("yLoad_input"));
        yLoad_input->setGeometry(QRect(580, 490, 67, 31));
        yLoad_input->setDecimals(10);
        yLoad_input->setMinimum(-1000000.000000000000000);
        yLoad_input->setMaximum(1000000.000000000000000);
        myLoad_input = new QDoubleSpinBox(centralwidget);
        myLoad_input->setObjectName(QString::fromUtf8("myLoad_input"));
        myLoad_input->setEnabled(false);
        myLoad_input->setGeometry(QRect(580, 550, 67, 31));
        myLoad_input->setDecimals(10);
        myLoad_input->setMinimum(-1000000.000000000000000);
        myLoad_input->setMaximum(1000000.000000000000000);
        mzLoad_input = new QDoubleSpinBox(centralwidget);
        mzLoad_input->setObjectName(QString::fromUtf8("mzLoad_input"));
        mzLoad_input->setGeometry(QRect(660, 550, 67, 31));
        mzLoad_input->setDecimals(10);
        mzLoad_input->setMinimum(-1000000.000000000000000);
        mzLoad_input->setMaximum(1000000.000000000000000);
        SubmitModel = new QPushButton(centralwidget);
        SubmitModel->setObjectName(QString::fromUtf8("SubmitModel"));
        SubmitModel->setGeometry(QRect(1030, 630, 141, 30));
        HybridCheck = new QCheckBox(centralwidget);
        HybridCheck->setObjectName(QString::fromUtf8("HybridCheck"));
        HybridCheck->setGeometry(QRect(100, 520, 71, 28));
        SwitchDimButton = new QPushButton(centralwidget);
        SwitchDimButton->setObjectName(QString::fromUtf8("SwitchDimButton"));
        SwitchDimButton->setGeometry(QRect(220, 20, 121, 30));
        DimText = new QTextEdit(centralwidget);
        DimText->setObjectName(QString::fromUtf8("DimText"));
        DimText->setGeometry(QRect(130, 20, 81, 31));
        Mass_Input = new QDoubleSpinBox(centralwidget);
        Mass_Input->setObjectName(QString::fromUtf8("Mass_Input"));
        Mass_Input->setGeometry(QRect(20, 140, 67, 31));
        Mass_Input->setDecimals(10);
        Mass_Input->setMaximum(10000000000000000000.000000000000000);
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(30, 120, 61, 22));
        selfWeightCheck = new QCheckBox(centralwidget);
        selfWeightCheck->setObjectName(QString::fromUtf8("selfWeightCheck"));
        selfWeightCheck->setGeometry(QRect(140, 140, 111, 28));
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(40, 500, 31, 22));
        rho_input = new QDoubleSpinBox(centralwidget);
        rho_input->setObjectName(QString::fromUtf8("rho_input"));
        rho_input->setGeometry(QRect(20, 520, 67, 31));
        rho_input->setDecimals(10);
        rho_input->setMaximum(1000000.000000000000000);
        plotModelButton = new QPushButton(centralwidget);
        plotModelButton->setObjectName(QString::fromUtf8("plotModelButton"));
        plotModelButton->setGeometry(QRect(1030, 670, 141, 30));
        HybridProps = new QPushButton(centralwidget);
        HybridProps->setObjectName(QString::fromUtf8("HybridProps"));
        HybridProps->setEnabled(false);
        HybridProps->setGeometry(QRect(180, 520, 71, 30));
        submitEQ = new QPushButton(centralwidget);
        submitEQ->setObjectName(QString::fromUtf8("submitEQ"));
        submitEQ->setGeometry(QRect(1050, 120, 91, 30));
        plainTextEdit = new QPlainTextEdit(centralwidget);
        plainTextEdit->setObjectName(QString::fromUtf8("plainTextEdit"));
        plainTextEdit->setGeometry(QRect(1000, 70, 191, 41));
        scale = new QDoubleSpinBox(centralwidget);
        scale->setObjectName(QString::fromUtf8("scale"));
        scale->setGeometry(QRect(1120, 240, 67, 31));
        scale->setDecimals(4);
        scale->setMaximum(100000000000000.000000000000000);
        dtold = new QDoubleSpinBox(centralwidget);
        dtold->setObjectName(QString::fromUtf8("dtold"));
        dtold->setGeometry(QRect(1120, 280, 67, 31));
        dtold->setDecimals(5);
        dt = new QDoubleSpinBox(centralwidget);
        dt->setObjectName(QString::fromUtf8("dt"));
        dt->setGeometry(QRect(1120, 320, 67, 31));
        dt->setDecimals(5);
        alpha = new QDoubleSpinBox(centralwidget);
        alpha->setObjectName(QString::fromUtf8("alpha"));
        alpha->setGeometry(QRect(1120, 360, 67, 31));
        alpha->setDecimals(5);
        alpha->setMinimum(-5.000000000000000);
        alpha->setMaximum(0.000000000000000);
        zeta = new QDoubleSpinBox(centralwidget);
        zeta->setObjectName(QString::fromUtf8("zeta"));
        zeta->setGeometry(QRect(990, 450, 67, 31));
        zeta->setDecimals(6);
        zeta->setMaximum(1.990000000000000);
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(1000, 210, 68, 22));
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(1080, 210, 68, 22));
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(1160, 210, 68, 22));
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(1000, 240, 101, 22));
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(1000, 280, 101, 22));
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(1000, 320, 101, 22));
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(1000, 360, 101, 22));
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(990, 420, 201, 22));
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(990, 480, 51, 22));
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(1070, 480, 51, 22));
        label_46 = new QLabel(centralwidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(1150, 480, 51, 22));
        submitDynOp = new QPushButton(centralwidget);
        submitDynOp->setObjectName(QString::fromUtf8("submitDynOp"));
        submitDynOp->setGeometry(QRect(990, 520, 201, 30));
        plainTextEdit_2 = new QPlainTextEdit(centralwidget);
        plainTextEdit_2->setObjectName(QString::fromUtf8("plainTextEdit_2"));
        plainTextEdit_2->setGeometry(QRect(1040, 560, 101, 31));
        dir1 = new QDoubleSpinBox(centralwidget);
        dir1->setObjectName(QString::fromUtf8("dir1"));
        dir1->setGeometry(QRect(990, 180, 67, 31));
        dir1->setDecimals(2);
        dir1->setMinimum(-99.000000000000000);
        dir2 = new QDoubleSpinBox(centralwidget);
        dir2->setObjectName(QString::fromUtf8("dir2"));
        dir2->setGeometry(QRect(1070, 180, 67, 31));
        dir2->setDecimals(2);
        dir2->setMinimum(-99.000000000000000);
        dir3 = new QDoubleSpinBox(centralwidget);
        dir3->setObjectName(QString::fromUtf8("dir3"));
        dir3->setGeometry(QRect(1150, 180, 67, 31));
        dir3->setDecimals(2);
        dir3->setMinimum(-99.000000000000000);
        Mode1 = new QDoubleSpinBox(centralwidget);
        Mode1->setObjectName(QString::fromUtf8("Mode1"));
        Mode1->setGeometry(QRect(1070, 450, 67, 31));
        Mode1->setDecimals(0);
        Mode1->setMaximum(15.000000000000000);
        Mode2 = new QDoubleSpinBox(centralwidget);
        Mode2->setObjectName(QString::fromUtf8("Mode2"));
        Mode2->setGeometry(QRect(1150, 450, 67, 31));
        Mode2->setDecimals(0);
        Mode2->setMaximum(15.000000000000000);
        REL1 = new QDoubleSpinBox(centralwidget);
        REL1->setObjectName(QString::fromUtf8("REL1"));
        REL1->setGeometry(QRect(80, 630, 67, 31));
        REL1->setMinimum(-1.000000000000000);
        REL1->setMaximum(1000000000000.000000000000000);
        REL1->setValue(-1.000000000000000);
        REL2 = new QDoubleSpinBox(centralwidget);
        REL2->setObjectName(QString::fromUtf8("REL2"));
        REL2->setGeometry(QRect(160, 630, 67, 31));
        REL2->setMinimum(-1.000000000000000);
        REL2->setMaximum(1000000000000.000000000000000);
        REL2->setValue(-1.000000000000000);
        REL3 = new QDoubleSpinBox(centralwidget);
        REL3->setObjectName(QString::fromUtf8("REL3"));
        REL3->setGeometry(QRect(240, 630, 67, 31));
        REL3->setMinimum(-1.000000000000000);
        REL3->setMaximum(1000000000000.000000000000000);
        REL3->setValue(-1.000000000000000);
        REL7 = new QDoubleSpinBox(centralwidget);
        REL7->setObjectName(QString::fromUtf8("REL7"));
        REL7->setEnabled(false);
        REL7->setGeometry(QRect(340, 630, 67, 31));
        REL7->setMinimum(-1.000000000000000);
        REL7->setMaximum(1000000000000.000000000000000);
        REL7->setValue(-1.000000000000000);
        REL8 = new QDoubleSpinBox(centralwidget);
        REL8->setObjectName(QString::fromUtf8("REL8"));
        REL8->setEnabled(false);
        REL8->setGeometry(QRect(420, 630, 67, 31));
        REL8->setMinimum(-1.000000000000000);
        REL8->setMaximum(1000000000000.000000000000000);
        REL8->setValue(-1.000000000000000);
        REL9 = new QDoubleSpinBox(centralwidget);
        REL9->setObjectName(QString::fromUtf8("REL9"));
        REL9->setEnabled(false);
        REL9->setGeometry(QRect(500, 630, 67, 31));
        REL9->setMinimum(-1.000000000000000);
        REL9->setMaximum(1000000000000.000000000000000);
        REL9->setValue(-1.000000000000000);
        REL4 = new QDoubleSpinBox(centralwidget);
        REL4->setObjectName(QString::fromUtf8("REL4"));
        REL4->setGeometry(QRect(80, 670, 67, 31));
        REL4->setMinimum(-1.000000000000000);
        REL4->setMaximum(1000000000000.000000000000000);
        REL4->setValue(-1.000000000000000);
        REL5 = new QDoubleSpinBox(centralwidget);
        REL5->setObjectName(QString::fromUtf8("REL5"));
        REL5->setGeometry(QRect(160, 670, 67, 31));
        REL5->setMinimum(-1.000000000000000);
        REL5->setMaximum(1000000000000.000000000000000);
        REL5->setValue(-1.000000000000000);
        REL6 = new QDoubleSpinBox(centralwidget);
        REL6->setObjectName(QString::fromUtf8("REL6"));
        REL6->setGeometry(QRect(240, 670, 67, 31));
        REL6->setMinimum(-1.000000000000000);
        REL6->setMaximum(1000000000000.000000000000000);
        REL6->setValue(-1.000000000000000);
        REL10 = new QDoubleSpinBox(centralwidget);
        REL10->setObjectName(QString::fromUtf8("REL10"));
        REL10->setEnabled(false);
        REL10->setGeometry(QRect(340, 670, 67, 31));
        REL10->setMinimum(-1.000000000000000);
        REL10->setMaximum(1000000000000.000000000000000);
        REL10->setValue(-1.000000000000000);
        REL11 = new QDoubleSpinBox(centralwidget);
        REL11->setObjectName(QString::fromUtf8("REL11"));
        REL11->setEnabled(false);
        REL11->setGeometry(QRect(420, 670, 67, 31));
        REL11->setMinimum(-1.000000000000000);
        REL11->setMaximum(1000000000000.000000000000000);
        REL11->setValue(-1.000000000000000);
        REL12 = new QDoubleSpinBox(centralwidget);
        REL12->setObjectName(QString::fromUtf8("REL12"));
        REL12->setEnabled(false);
        REL12->setGeometry(QRect(500, 670, 67, 31));
        REL12->setMinimum(-1.000000000000000);
        REL12->setMaximum(1000000000000.000000000000000);
        REL12->setValue(-1.000000000000000);
        ElREL = new QTextEdit(centralwidget);
        ElREL->setObjectName(QString::fromUtf8("ElREL"));
        ElREL->setGeometry(QRect(590, 630, 391, 111));
        label_47 = new QLabel(centralwidget);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(20, 600, 211, 22));
        CustomEl = new QPushButton(centralwidget);
        CustomEl->setObjectName(QString::fromUtf8("CustomEl"));
        CustomEl->setEnabled(false);
        CustomEl->setGeometry(QRect(160, 560, 91, 30));
        CustomCheck = new QCheckBox(centralwidget);
        CustomCheck->setObjectName(QString::fromUtf8("CustomCheck"));
        CustomCheck->setGeometry(QRect(30, 560, 81, 28));
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(310, 630, 20, 81));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(0, 320, 491, 21));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(0, 210, 961, 21));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(480, 0, 16, 601));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(950, 0, 16, 601));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(490, 590, 831, 21));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(986, 600, 31, 211));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralwidget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(0, 0, 1251, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralwidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(490, 410, 471, 16));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralwidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(1233, 0, 31, 601));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        label_48 = new QLabel(centralwidget);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(20, 630, 71, 22));
        label_49 = new QLabel(centralwidget);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(20, 670, 71, 22));
        HybridDof1 = new QDoubleSpinBox(centralwidget);
        HybridDof1->setObjectName(QString::fromUtf8("HybridDof1"));
        HybridDof1->setGeometry(QRect(1100, 730, 67, 31));
        HybridDof1->setDecimals(0);
        HybridDof1->setMaximum(15.000000000000000);
        HybridDof2 = new QDoubleSpinBox(centralwidget);
        HybridDof2->setObjectName(QString::fromUtf8("HybridDof2"));
        HybridDof2->setGeometry(QRect(1190, 730, 67, 31));
        HybridDof2->setDecimals(0);
        HybridDof2->setMaximum(15.000000000000000);
        ModelDisplay = new QPlainTextEdit(centralwidget);
        ModelDisplay->setObjectName(QString::fromUtf8("ModelDisplay"));
        ModelDisplay->setGeometry(QRect(1200, 630, 101, 31));
        label_50 = new QLabel(centralwidget);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(1100, 710, 51, 22));
        label_51 = new QLabel(centralwidget);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(1190, 710, 51, 22));
        label_52 = new QLabel(centralwidget);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(1030, 710, 51, 22));
        label_53 = new QLabel(centralwidget);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(1020, 730, 71, 22));
        label_54 = new QLabel(centralwidget);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(1010, 750, 71, 22));
        pickActuators = new QPushButton(centralwidget);
        pickActuators->setObjectName(QString::fromUtf8("pickActuators"));
        pickActuators->setGeometry(QRect(1120, 770, 111, 30));
        PSAS->setCentralWidget(centralwidget);
        menubar = new QMenuBar(PSAS);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1325, 20));
        PSAS->setMenuBar(menubar);
        statusbar = new QStatusBar(PSAS);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        PSAS->setStatusBar(statusbar);

        retranslateUi(PSAS);

        QMetaObject::connectSlotsByName(PSAS);
    } // setupUi

    void retranslateUi(QMainWindow *PSAS)
    {
        PSAS->setWindowTitle(QCoreApplication::translate("PSAS", "MainWindow", nullptr));
        actionGround_Motion->setText(QCoreApplication::translate("PSAS", "Ground Motion", nullptr));
        add_node->setText(QCoreApplication::translate("PSAS", "Add Node", nullptr));
        remove_node->setText(QCoreApplication::translate("PSAS", "Remove Node", nullptr));
        add_element_button->setText(QCoreApplication::translate("PSAS", "Add Element", nullptr));
        label->setText(QCoreApplication::translate("PSAS", "E", nullptr));
        label_2->setText(QCoreApplication::translate("PSAS", "A", nullptr));
        label_3->setText(QCoreApplication::translate("PSAS", "J", nullptr));
        label_4->setText(QCoreApplication::translate("PSAS", "v", nullptr));
        label_5->setText(QCoreApplication::translate("PSAS", "Iy", nullptr));
        label_6->setText(QCoreApplication::translate("PSAS", "Iz", nullptr));
        El_prop_button->setText(QCoreApplication::translate("PSAS", "Insert El Prop", nullptr));
        label_7->setText(QCoreApplication::translate("PSAS", "Element", nullptr));
        label_9->setText(QCoreApplication::translate("PSAS", "i node", nullptr));
        label_10->setText(QCoreApplication::translate("PSAS", "j node", nullptr));
        label_11->setText(QCoreApplication::translate("PSAS", "x pos", nullptr));
        label_12->setText(QCoreApplication::translate("PSAS", "y pos", nullptr));
        label_13->setText(QCoreApplication::translate("PSAS", "z pos", nullptr));
        label_8->setText(QCoreApplication::translate("PSAS", "Node", nullptr));
        label_14->setText(QCoreApplication::translate("PSAS", "Bz", nullptr));
        label_15->setText(QCoreApplication::translate("PSAS", "Bx", nullptr));
        label_16->setText(QCoreApplication::translate("PSAS", "By", nullptr));
        label_17->setText(QCoreApplication::translate("PSAS", "Brz", nullptr));
        label_18->setText(QCoreApplication::translate("PSAS", "Brx", nullptr));
        label_19->setText(QCoreApplication::translate("PSAS", "Bry", nullptr));
        label_20->setText(QCoreApplication::translate("PSAS", "wz", nullptr));
        label_21->setText(QCoreApplication::translate("PSAS", "wx", nullptr));
        label_22->setText(QCoreApplication::translate("PSAS", "ry", nullptr));
        label_23->setText(QCoreApplication::translate("PSAS", "Element", nullptr));
        label_24->setText(QCoreApplication::translate("PSAS", "rz", nullptr));
        label_25->setText(QCoreApplication::translate("PSAS", "wy", nullptr));
        label_26->setText(QCoreApplication::translate("PSAS", "rx", nullptr));
        label_27->setText(QCoreApplication::translate("PSAS", "x Load", nullptr));
        label_28->setText(QCoreApplication::translate("PSAS", "Node", nullptr));
        label_29->setText(QCoreApplication::translate("PSAS", "z Load", nullptr));
        label_30->setText(QCoreApplication::translate("PSAS", "my", nullptr));
        label_31->setText(QCoreApplication::translate("PSAS", "mx", nullptr));
        label_32->setText(QCoreApplication::translate("PSAS", "mz", nullptr));
        label_33->setText(QCoreApplication::translate("PSAS", "y Load", nullptr));
        remove_element_button->setText(QCoreApplication::translate("PSAS", "Remove El", nullptr));
        Boundary_Button->setText(QCoreApplication::translate("PSAS", "Insert Boundary ", nullptr));
        El_Load_Button->setText(QCoreApplication::translate("PSAS", "Insert El Load", nullptr));
        Nodal_Load_Button->setText(QCoreApplication::translate("PSAS", "Insert Nodal Load", nullptr));
        SubmitModel->setText(QCoreApplication::translate("PSAS", "Submit Model", nullptr));
        HybridCheck->setText(QCoreApplication::translate("PSAS", "Hybrid", nullptr));
        SwitchDimButton->setText(QCoreApplication::translate("PSAS", "Switch Dim", nullptr));
        label_34->setText(QCoreApplication::translate("PSAS", "Mass", nullptr));
        selfWeightCheck->setText(QCoreApplication::translate("PSAS", "Self Weight", nullptr));
        label_35->setText(QCoreApplication::translate("PSAS", "rho", nullptr));
        plotModelButton->setText(QCoreApplication::translate("PSAS", "Plot Model", nullptr));
        HybridProps->setText(QCoreApplication::translate("PSAS", "Hyb Prop", nullptr));
        submitEQ->setText(QCoreApplication::translate("PSAS", "Submit GM", nullptr));
        label_36->setText(QCoreApplication::translate("PSAS", "xdir", nullptr));
        label_37->setText(QCoreApplication::translate("PSAS", "ydir", nullptr));
        label_38->setText(QCoreApplication::translate("PSAS", "zdir", nullptr));
        label_39->setText(QCoreApplication::translate("PSAS", "Scale Factor", nullptr));
        label_40->setText(QCoreApplication::translate("PSAS", "dt of file", nullptr));
        label_41->setText(QCoreApplication::translate("PSAS", "dt new", nullptr));
        label_42->setText(QCoreApplication::translate("PSAS", "alpha", nullptr));
        label_43->setText(QCoreApplication::translate("PSAS", "Rayleigh Damping Params", nullptr));
        label_44->setText(QCoreApplication::translate("PSAS", "Zeta", nullptr));
        label_45->setText(QCoreApplication::translate("PSAS", "Mode 1", nullptr));
        label_46->setText(QCoreApplication::translate("PSAS", "Mode 2", nullptr));
        submitDynOp->setText(QCoreApplication::translate("PSAS", "Submit Dynamic Options", nullptr));
        label_47->setText(QCoreApplication::translate("PSAS", "Element Releases", nullptr));
        CustomEl->setText(QCoreApplication::translate("PSAS", "Custom El", nullptr));
        CustomCheck->setText(QCoreApplication::translate("PSAS", "Custom", nullptr));
        label_48->setText(QCoreApplication::translate("PSAS", "i Node", nullptr));
        label_49->setText(QCoreApplication::translate("PSAS", "j Node", nullptr));
        label_50->setText(QCoreApplication::translate("PSAS", "hDOF 1", nullptr));
        label_51->setText(QCoreApplication::translate("PSAS", "hDOF 2", nullptr));
        label_52->setText(QCoreApplication::translate("PSAS", "Pick", nullptr));
        label_53->setText(QCoreApplication::translate("PSAS", "Actuator", nullptr));
        label_54->setText(QCoreApplication::translate("PSAS", "(1 indexed)", nullptr));
        pickActuators->setText(QCoreApplication::translate("PSAS", "Pick Actuators", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PSAS: public Ui_PSAS {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PSAS_H
